### ISSUE TITLE
Create an Issue Template

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/GitHub-ReadMe#1]
As a part of GSSoC 23, I would like someone to create an Issue Template that gives the following choices.

1. New Feature (Landing Page)
2. New Feature (App)
3. Bug (Landing Page)
4. Bug (App)
5. New Component (App)

And it should automatically give the default GSSoC Label. Please explain how you're planning to do it while you wanna grab this issue.

**Comment by DSR1729** [comment]
Hey @praveenscience, here is an issue template.👇

## Issue Description


### Type of Issue

Please select the type of issue from the following choices:

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)

### Additional Details

Please provide any additional details or context about the issue.

## Labels

To automatically assign a label to an issue in GitHub, you can make use of GitHub Actions. 
Here's how you can set it up:👇

1. Click on the "Actions" tab at the top of the repository.
2. Click on the "Set up a workflow yourself" or "New workflow" button.
3. Create a new YAML file auto_label.yml and paste the following code into it:👇

name: Auto Label Issue
on:
  issues:
    types: [opened]

jobs:
  labelIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue title includes GSSoC23
        id: check_issue_title
        run: echo "::set-output name=contains_gssoc23::$(echo ${{ github.event.issue.title }} | grep -c 'GSSoC23')"

      - name: Add label to the issue
        if: steps.check_issue_title.outputs.contains_gssoc23 == '1'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: GSSoC23

4. This workflow will trigger whenever a new issue is opened (types: [opened]).
5. It checks if the issue title contains the string "GSSoC23" using grep. If the string is found, it sets the output contains_gssoc23 to '1'.
6. If the contains_gssoc23 output is '1', it adds the label "GSSoC23" to the issue using the actions-ecosystem/action-add-labels action.
7. Save the changes to the YAML file. Now, whenever a new issue is created with "GSSoC23" in its title, the "GSSoC23" label will be automatically assigned to it.

## Here is an image of the code you need to paste 👇

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/115932772/3c223591-ae03-4300-8183-e1922b08b8cd)

### Can you please assign this issue to me !

**Comment by praveenscience** [comment]
It's your @DSR1729

**Comment by praveenscience** [comment]
It's yours @DSR1729! 💪🏻

**Comment by AmanJain18** [comment]
I think instead of giving choice to tick check box ✅ we can create different issue template of respective Issues, so that we can set content requirements as per issues.
Eg: (Bug should have a mandatory Screenshot section for better understanding..., Step to reproduce, etc )
Wherever required

**Comment by DSR1729** [comment]
Hey @praveenscience here is the **PREVIEW** of my changes in the contributing.md file, suggest me changes that you want to see init !!

![Screenshot 2023-05-27 at 16-42-52 DSR1729_GitHub-ReadMe This is a React Project where you can customise your GitHub ReadMe with all the available cool things](https://github.com/CatsInTech/GitHub-ReadMe/assets/115932772/7c9ac1a4-cca6-4409-937f-9db41912930c)

**Comment by praveenscience** [comment]
@AmanJain18 Kindly try it out! Let's make it that way, that was the expected one. 💪🏻

**Comment by AmanJain18** [comment]
> @AmanJain18 Kindly try it out! Let's make it that way, that was the expected one. 💪🏻

Yes sure, Just let me know what Mandatory this to be asked while creating issue

**Comment by praveenscience** [comment]
Give the first pass based on other projects, let's improve on top of it... 😊

**Comment by AmanJain18** [comment]
This issue is completed and reslove mark it as close...

**Comment by praveenscience** [comment]
Resolved! Thanks! 😊
