### ISSUE TITLE
Improving the design and animation of navbar and making it scrollable with page

### ISSUE THREAD

**Issue by huamanraj** [CatsInTech/GitHub-ReadMe#125]
### Description of the bug. ✍🏻

navbar looks odd and also not hiding when we scroll down

### Current Behaviour

1. not hiding after scrolling 
2. looks flat color and odd

### Expected Behaviour

1. responsive and scrollable 
2. improved design, animation, hover effect and color combination 

### Screenshots

![Screenshot (7)](https://github.com/CatsInTech/GitHub-ReadMe/assets/113578582/ec60e7f3-6c3e-4489-aeb6-dddae5035ef0)

### Additional information

assign me this issue for gssoc 2023

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by kunal-2002** [comment]
I understand what has to be done here, so please assign me this issue under GSSOC'23

**Comment by s20bo1a** [comment]
I am also interested to work with this issue. please assign me.
