### ISSUE TITLE
🐞 [BUG_LP] - Navbar is sticked to the top

### ISSUE THREAD

**Issue by sumitkr2000** [CatsInTech/GitHub-ReadMe#127]
### Description of the bug. ✍🏻

Hey, @praveenscience It seems that the navbar is too much sticked to the top and that's why it is not looking good. Please assign me this issue. Thank you!

### Current Behaviour

Navbar sticked to the top

### Expected Behaviour

Some margin-top to the navbar

### Reproduction Steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by sumitkr2000** [comment]
@praveenscience Please assign me this issue so that I can start working on it.

**Comment by TMTanmay1** [comment]
@sumitkr2000 please assign this issue to me under ssoc'23

**Comment by sumitkr2000** [comment]
@praveenscience Please assign me this issue so that I can start working on it.
