### ISSUE TITLE
🐞 [BUG_WebApp] - Fix "Purchase Now" Button Redirect Bug and Update FAQ Section with Relevant Content

### ISSUE THREAD

**Issue by Nishitbaria** [CatsInTech/GitHub-ReadMe#135]
### Description of the bug. ✍🏻

There is a bug in the website where clicking the "Purchase Now" button redirects the user to the '/#' route instead of the intended destination for completing the purchase. This issue prevents users from successfully proceeding with the purchase process and disrupts the user experience. Additionally, the FAQ section of the website currently contains generic Lorem Ipsum text, which does not provide users with the necessary information or support. It is crucial to fix the redirect bug and update the FAQ section with relevant content to address these issues.

### Current Behaviour

Clicking the "Purchase Now" button redirects the user to the '/#' route instead of the expected destination for completing the purchase and lorem ipsum answers are written in FAQ.

### Expected Behaviour

Upon clicking the "Purchase Now" button, users should be directed to the appropriate destination for completing the purchase process successfully. The FAQ section should contain informative and relevant content that answers common user questions and provides necessary support.

### Reproduction Steps

```bash
1. Visit the website's home page.
2. Click the "Purchase Now" button.
3. Checkout FAQ section.
4. See error
```

### Screenshots

**Steps to Reproduce:**

### Additional information

 Please assign me this issue with appropriate lable,I will  make the page to be redirected after purchase now and also add relevant answers in FAQ section .

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by s20bo1a** [comment]
@praveenscience I would like to work on this issue.

**Comment by Nishitbaria** [comment]
@praveenscience I am already working on this issue
