### ISSUE TITLE
🚀 [New Feature] - Dockerize the application

### ISSUE THREAD

**Issue by abhinav-m22** [CatsInTech/GitHub-ReadMe#144]
### Describe the need for this component. ✍🏻

I want to containerize the application by creating a Dockerfile and a corresponding dockerignore file.

Dockerizing the application will enable us to package it along with its dependencies into a container, ensuring consistent and reliable deployments across different environments.

### Describe briefly how you would implement and plan to use this component.

```bash
By using Docker, we can easily spin up and scale multiple instances of the application, making it more robust and efficient.

This issue aims to implement Dockerization for the application, streamlining our deployment workflow and enhancing its overall performance and portability.
```

### Additional information

I want to work on this issue.
Please assign me the task under GSSoC'23.

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by AmanJain18** [comment]
@praveenscience Sir, Look what u have to say about this issue.✌🏻
