### ISSUE TITLE
🚀 [New Feature_LP] - Add GitHub link in Footer

### ISSUE THREAD

**Issue by blindaks** [CatsInTech/GitHub-ReadMe#167]
### Description of the enhancement. ✍🏻

I want to add GitHub link in the footer.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. I will add GitHub logo
2. I will link it to the corresponding GitHub account
```

### Screenshots Example (if applicable)

![Screenshot (34)](https://github.com/CatsInTech/GitHub-ReadMe/assets/128223364/994bf1fc-03d0-4bde-90c8-56f58c7cbcc8)

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by weblearner07** [comment]
Please assign me this issue under gssoc23'

**Comment by blindaks** [comment]
@CatsInTech Please assign this issue to me.

**Comment by spruhakar5** [comment]
Please assign me this issue under gssoc23'

**Comment by sakshimaluskar2** [comment]
Hey @praveenscience I am able to add  github link into footer footer section ,Please assign this issue to me.
