### ISSUE TITLE
[feature] add license

### ISSUE THREAD

**Issue by rohanmittal1163** [CatsInTech/GitHub-ReadMe#17]
hi @praveenscience seems like your github repo does not include license file.
I know the procedure to add license file and what to add in it. MIT would be suitable to it
pls assign me this issue under the ongoing open source contribution
thank you

**Comment by rohanmittal1163** [comment]
@praveenscience could you pls help me in downloading your github repo its not working with npm i or npm ci. what should i do  now

**Comment by praveenscience** [comment]
MIT is fine. 👍 

What's the problem are you facing? Any errors? Why is `npm ci` or `npm i` isn't working? Please add a screenshot so that I can guide you. 😊

**Comment by rohanmittal1163** [comment]
@praveenscience now got the issue. I have to update npm

**Comment by rohanmittal1163** [comment]
Hi @praveenscience pls add the respectove tags to this issue as it has been merged
Thank you

**Comment by praveenscience** [comment]
@rohanmittal1163 I am working in the Leaderboard team, don't worry, will be adding the tags for the merged PR without fail. Will take care of it. 😊

**Comment by praveenscience** [comment]
@rohanmittal1163 Issues need not have any tags or labels, FYKI. 😊
