### ISSUE TITLE
🐞 [BUG_WebApp] - Footer section not working

### ISSUE THREAD

**Issue by RitiChandak** [CatsInTech/GitHub-ReadMe#174]
### Description of the bug. ✍🏻

the links in the footer section is not working

### Current Behaviour

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/96969496/018f5a69-a6ca-4597-8fd7-46a8ed6804de)
by clicking on the links of social media or the content of the navbar it takes to the home page of the website 

### Expected Behaviour

when the links are clicked it should take to the respective pages or section

### Reproduction Steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by RitiChandak** [comment]
@praveenscience please assign me this issue under gssoc'23

**Comment by akankshabach** [comment]
I want to solve this issue please assign me .
Thank you!

**Comment by AmanJain18** [comment]
@RitiChandak This is the duplicate issue, also we currently don't have the actual social link where we can redirect it...
