### ISSUE TITLE
Implementation of Swagger API for better documentation and testing.

### ISSUE THREAD

**Issue by Saksham1005** [CatsInTech/GitHub-ReadMe#176]
### Description of the documentation deficiency / workflow suggestion. ✍🏻

Swagger API will help expose all the routes on a single URL. Thus helping developers to quickly test the APIs developed, that too on the browser itself.

A Sample of Swagger API is as follows-
![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/70437462/99ceba54-a1b1-4e18-af29-ffcd1162d30e)

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by pulkitxm** [comment]
I would like to work on this issue, Could you guide me how to start?

**Comment by praveenscience** [comment]
Tell me what you understood from this issue and what you are planning to work on this? Very curious to know @Pulkitxm

**Comment by praveenscience** [comment]
Closing as @Pulkitxm isn't interested anymore.
