### ISSUE TITLE
Create PR Templates

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/GitHub-ReadMe#2]
As a part of GSSoC 23, I would like someone to create a PR Template that takes up following options.

1. New Feature (Landing Page)
2. New Feature (App)
3. Bug (Landing Page)
4. Bug (App)
5. New Component (App)
6. Your Idea for Level (GSSoC)
7. Which Issue it Solves?

And it should automatically give the default GSSoC Label. Please explain how you're planning to do it while you wanna grab this issue.

**Comment by Kapileswar-Moharana** [comment]
Assign this to me under GSSoC'23

**Comment by Isha988** [comment]
> As a part of GSSoC 23, I would like someone to create a PR Template that takes up the following options.
> 
> 1. New Feature (Landing Page)
> 2. New Feature (App)
> 3. Bug (Landing Page)
> 4. Bug (App)
> 5. New Component (App)
> 6. Your Idea for Level (GSSoC)
> 7. Which Issue does it solve?
> 
> And it should automatically give the default GSSoC Label. Please explain how you're planning to do it while you wanna grab this issue.

Hey @praveenscience, I want to work on this issue.
I am thinking of creating a pr template with the following fields
1. Issue it closes/fixes.
2. Changes made
3. Options for the type of issues it solves (option mentioned in issue)
4. Screenshot (if any)
5. Additional information.

For automatically adding an Gssoc label, I am thinking of using GitHub issue-labeller. I don't know much about it but want to work on it and learn more about it.

**Comment by praveenscience** [comment]
Amazing, let's go @Isha988! 💪🏻

**Comment by Isha988** [comment]
> Amazing, let's go @Isha988! 💪🏻 Also check with GitHub, they can do forms right now. Let's use that. 😁 Check out: [Syntax for issue forms - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

@praveenscience as per my knowledge form feature can be used in the .yml file but the pr template is created in the .md file.
Please correct me if I am wrong.

**Comment by praveenscience** [comment]
I believe so... 💪🏻

**Comment by Isha988** [comment]
Hi, @praveenscience I am done with creating the PR template and configuring the labeler but I don't know how to check whether it is working all right or not.
Do you have any way of checking it  or should I create a PR for merging changes?

**Comment by praveenscience** [comment]
What's the source? Just raise the PR, we'll see if that works or not... Don't worry...

**Comment by Isha988** [comment]
> What's the source? Just raise the PR, we'll see if that works or not... Don't worry...

Okay

**Comment by praveenscience** [comment]
![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/1830380/fb747d99-0903-4467-8632-a5544030cd37)

This doesn't seem to create a form buddy?

**Comment by praveenscience** [comment]
Can you try this once again for me please? [Syntax for issue forms - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by Isha988** [comment]
> ![image](https://user-images.githubusercontent.com/1830380/241573079-fb747d99-0903-4467-8632-a5544030cd37.png)
> 
> This doesn't seem to create a form buddy?

Ya, because It is a md file.
I checked for pr template of repo, all of them are similar to this.

**Comment by Isha988** [comment]
> Can you try this once again for me please? [Syntax for issue forms - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

Ok wait, I will

**Comment by Isha988** [comment]
> Can you try this once again for me please? [Syntax for issue forms - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

![Screenshot_2023-05-28-21-55-34-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/CatsInTech/GitHub-ReadMe/assets/89572340/8361d0ab-f1ec-4529-b058-02bdefbdf1d8)

**Comment by praveenscience** [comment]
😑
