### ISSUE TITLE
Add "Back to top" button in ReadMe.md

### ISSUE THREAD

**Issue by Swastik007sharma** [CatsInTech/GitHub-ReadMe#32]
Could we add a 'Back to Top' button for contributors' convenience? It would allow users to easily navigate back to the top with a single click. Also, I'd be happy to take on this issue if assigned. Thank you!

**Comment by praveenscience** [comment]
I don't see a use for this, but given that it's super long, maybe yes, along with this, can you also add a ToC (Table of Contents)? Thanks! 😊

**Comment by Swastik007sharma** [comment]
> I don't see a use for this, but given that it's super long, maybe yes, along with this, can you also add a ToC (Table of Contents)? Thanks! 😊

Sure, I appreciate your suggestions. I have a couple of questions before proceeding:

1. Should I add the "Go Back to Top" button after every section or only at the very end?
2. Which type of button would you prefer? We can go with:
    *  "Back to top" - simple words
    *  "[⬆️ Back to top]" - text with emoji
    * [![Go Back to Top](https://img.shields.io/badge/Go%20Back%20to-Top-blue)]() - banner-like button
3. Regarding the Table of Contents (ToC), should I include headings only or both headings and sub-headings?

Let me know your preferences, and I'll proceed accordingly.

**Comment by praveenscience** [comment]
1. Use your ideas.
2. Again, use your idea to make sure it looks amazingly nice!
3. Add Headings and Subheadings like as a hierarchical list.

Example for point 3:

* [Introduction](https://example.com)
  * [About Us](https://example.com)
  * [Motivation](https://example.com)
* [Contamination](https://example.com)
  * [Water Contamination](https://example.com)
  * [Air Contamination](https://example.com)
* [Comedy](https://example.com)
  * [Stand-Up](https://example.com)
  * [Dark](https://example.com)
  * [Mokka](https://example.com)
* [Installation](https://example.com)
  * [Mac](https://example.com)
  * [Windows](https://example.com)
  * [Linux](https://example.com)

**Comment by praveenscience** [comment]
Hey, let's have text with emoji please? 😊
