### ISSUE TITLE
Update `git clone` Command in `README.md` Installation Instructions

### ISSUE THREAD

**Issue by vinitshahdeo** [CatsInTech/GitHub-ReadMe#34]
The current `git clone` command provided in the [Installation & Running Instructions](https://github.com/CatsInTech/GitHub-ReadMe/blob/main/ReadMe.md#installation--running-instructions) section of the README.md file is incorrect and needs to be updated.

The existing command suggests using a generic URL for cloning the repository, which may cause confusion for users trying to follow the installation instructions. To ensure clarity and accuracy, it is recommended to replace the current command with the following:

```bash
git clone https://github.com/<Your-GitHub-Username>/GitHub-ReadMe.git
```

This updated command provides a specific URL that users can customize by replacing `<Your-GitHub-Username>` with their actual GitHub username. By making this change, it will help users correctly clone the repository and proceed with the installation process without encountering any unnecessary difficulties.

**Comment by AmanJain18** [comment]
Justby adding - first fork the original repository and then clone it from own acc will also do...

**Comment by praveenscience** [comment]
Up for grabs! 👍

**Comment by tayyab-ilyas** [comment]
> Up for grabs! 👍

I can fix this

**Comment by praveenscience** [comment]
Go for it @tayyab-ilyas
