### ISSUE TITLE
Add Code of Conduct to the Repository

### ISSUE THREAD

**Issue by vinitshahdeo** [CatsInTech/GitHub-ReadMe#36]
It is essential to foster a welcoming and inclusive environment for all contributors and maintain a respectful community within the project. To ensure this, it is recommended to add a Code of Conduct to the repository.

A Code of Conduct outlines the expected behavior and sets clear guidelines for all participants involved in the project. It helps create a safe and harassment-free space, promoting constructive discussions and collaboration.

I suggest incorporating a Code of Conduct file, such as `CODE_OF_CONDUCT.md`, in the root directory of the repository. This file should include the following:

**1. A statement emphasizing the commitment to fostering an inclusive and respectful environment for all contributors.
2. Clear guidelines on expected behavior, including examples of unacceptable behavior.
3. Instructions for reporting any violations of the Code of Conduct.
4. Information on how reports will be addressed and any consequences for violations.
5. Contact details for individuals who can address Code of Conduct issues or concerns.**

By including a Code of Conduct, we establish a strong foundation for a positive and inclusive community. It will provide contributors with a reference point for appropriate conduct, as well as ensure that any potential issues are addressed promptly and effectively.

> **Note** **Here's a sample [`CODE_OF_CONDUCT.md`](https://github.com/vinitshahdeo/peerlist-readme-badge/blob/main/CODE_OF_CONDUCT.md)**

cc/ @praveenscience

**Comment by praveenscience** [comment]
Or up for grabs! 😊

**Comment by praveenscience** [comment]
@Anshika-Jain02 Check this out. 😊

**Comment by AmanJain18** [comment]
@praveenscience 
Made new pr ref this issue and issue #39 
And added code of conduct as it's been 6 days. -> no response

**Comment by praveenscience** [comment]
I couldn't find the PR @AmanJain18

**Comment by praveenscience** [comment]
Hey @AmanJain18, also @vinitshahdeo isn't just a contributor, he's one of the finest Developers and DevRels and one of the admins of this Cats in Tech! 💪

**Comment by AmanJain18** [comment]
> Hey @AmanJain18, also @vinitshahdeo isn't just a contributor, he's one of the finest Developers and DevRels and one of the admins of this Cats in Tech! 💪 

Oops, Sorry my bad, i will always keep this in my mind ❤️✌🏻
