### ISSUE TITLE
Use `README.md` / `CONTRIBUTING.md` / `CODE_OF_CONDUCT.md`

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/GitHub-ReadMe#39]
### Discussed in https://github.com/CatsInTech/GitHub-ReadMe/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **vinitshahdeo** May 28, 2023</sup>
Let's use `README.md` / `CONTRIBUTING.md` / `CODE_OF_CONDUCT.md` in GitHub repositories.

- On GitHub, the commonly used and recognized convention for the filename of the README file is "**README.md**". This is case-sensitive, so it should be written in uppercase for "README" and lowercase for ".md" (Markdown file extension). Using "README.md" as the filename ensures compatibility and consistency across different repositories and platforms. It is also the default filename that GitHub recognizes and displays prominently on the repository's main page. While some platforms may accept alternative filename variations like "Readme.md" or "readme.md", it is generally recommended to follow the "README.md" convention for better consistency and compatibility within the GitHub ecosystem.

- On GitHub, the convention for the filename of the contributing guidelines file is typically "**CONTRIBUTING.md**". This convention is widely recognized and followed by many open-source projects and repositories. By using "CONTRIBUTING.md" as the filename, you ensure consistency and compatibility with other repositories and projects on GitHub. This naming convention is also recognized by various tools and integrations that rely on standard file naming conventions for contributing guidelines.

- GitHub recognizes "**CODE_OF_CONDUCT.md**" as the default filename for the Code of Conduct file. Using this convention ensures consistency and compatibility with other repositories and projects on the platform. It also aligns with the expectations of various tools and integrations that rely on standard file naming conventions for Code of Conduct files.

@praveenscience wdyt?</div>

**Comment by AmanJain18** [comment]
Should I rename the file according to above specified naming convention and CODE_OF_CONDUCT.md will be added from Issue #36

**Comment by AmanJain18** [comment]
@praveenscience 
Completed this also.
Some Contributors ask me regarding level label ?
And if you don't mind, can u grant me the right as collaborator, so that i will be able to review codes and manage issues and prs.
✌🏻😉

**Comment by praveenscience** [comment]
@AmanJain18 Giving you the rights, don't worry... Just sorting the labels... 😊
