### ISSUE TITLE
Add a contact us heading in webpage

### ISSUE THREAD

**Issue by prathanab** [CatsInTech/GitHub-ReadMe#4]
Add a contact us heading in webpage.

**Comment by prathanab** [comment]
assign this to me @praveenscience

**Comment by praveenscience** [comment]
Can you clarify it clearly, it's already there right? 🤔 Why did you mention GSSoC 23? I specifically asked folks not to mention it right? Again, is this for the App or the Landing Page? What's your plan of solution? Explain everything before getting assigned.

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/1830380/d0d134c3-1178-45b2-8835-a073ad11f037)

**Comment by prathanab** [comment]
Like this...

![IMG_20230527_124027](https://github.com/CatsInTech/GitHub-ReadMe/assets/121685069/1642aa8d-b0b7-466d-a0f6-be8541e46f9c)

**Comment by prathanab** [comment]
For the landing page.

**Comment by praveenscience** [comment]
Okay I still don't get it, but yea, give me the first pass, I'll review it.

Make sure you follow the prettier rules. 💪🏻

**Comment by prathanab** [comment]
Okay
