### ISSUE TITLE
Correcting grammar and Capitalization errors in the README.MD 

### ISSUE THREAD

**Issue by thakurdiwakar** [CatsInTech/GitHub-ReadMe#42]
Hey, I am a GSSOC contributor. Could you please assign me this task?

**Comment by praveenscience** [comment]
Please explain correctly, also your English isn't UK / India English. Exactly what you are planning to do? Thanks.

Also why did you mention GSSoC '23? I clearly told in the ReadMe, not to mention it right? 🤔

**Comment by praveenscience** [comment]
Okay, I am still confused, let's go... 😊
