### ISSUE TITLE
🐞 [BUG_LP] - App screenshots do not fit exactly in the mobile frame

### ISSUE THREAD

**Issue by kartikjoshi267** [CatsInTech/GitHub-ReadMe#47]
### Description

Apps screenshots do not fit exactly inside the mobile frame under the Show Our App Screenshots section.

### Current Behaviour

The images do not fit the mobile frame thus hiding data.

### Expected Behaviour

The images should fit the mobile frame without hiding any data so that it looks as if they are inside a real phone.

### Screenshots

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/96565730/9ab5f395-a395-43e9-b5af-0b70ecff0633)

### Additional information

Can you assign me with this issue?

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by praveenscience** [comment]
I am not really sure what you're suggesting, anyway, give it a go! 💪

**Comment by AmanJain18** [comment]
@kartikjoshi267 sync ur repo img branch, then make a pr
