### ISSUE TITLE
📚 [Documentation] - Adding repo badges in README.

### ISSUE THREAD

**Issue by mukul314** [CatsInTech/GitHub-ReadMe#48]
We can add badges in the ReadME that show the statistics of the repository.

Something like this maybe?
<img width="451" alt="2023-05-30 10_49_15-apoorvaron_Shorty_ • Shortens link and customize it according to user’s need  - " src="https://github.com/CatsInTech/GitHub-ReadMe/assets/76463001/6cd0dbff-fc24-4eea-8876-2bf4471c255a">

@praveenscience , I'd like to work on this issue.

**Comment by praveenscience** [comment]
I was about to ask for this, thanks @mukul314, waiting for your contribution! 😊

**Comment by praveenscience** [comment]
But it's already done by @mukul314 in #69 right?

**Comment by AmanJain18** [comment]
Ya, Thats because it is not merged. it's in checking phase.

**Comment by AmanJain18** [comment]
@codeburn12 Read what i have mentioned above, the PR is not merged yet, so how can we close this issue ?

**Comment by praveenscience** [comment]
@codeburn12 Why don't you add enhancements to the same? Happy to merge! 😊
