### ISSUE TITLE
📚 [Workflow] - To add workflow that will great the contributors on opening Issues and PRs

### ISSUE THREAD

**Issue by AmanJain18** [CatsInTech/GitHub-ReadMe#51]
### Description of the documentation deficiency / workflow suggestion. ✍🏻

To add workflow that will great the contributors on opening **Issues** and **PRs** with **Custom Message.** 
That will **automate** the process and flow...

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by AmanJain18** [comment]
Please assign it to me @praveenscience 
PS: Labeler action bot works perfectly ✌🏻

**Comment by praveenscience** [comment]
Go for it! 💪

**Comment by AmanJain18** [comment]
SuccessFully Implemented This functionality... 💪🏻✌🏻🚀
