### ISSUE TITLE
🐞 [BUG_LP] - Removing dropdown from home button

### ISSUE THREAD

**Issue by ShubhaSwarup** [CatsInTech/GitHub-ReadMe#56]
### Description of the bug. ✍🏻

In home button of navigation bar there is a drop down with several options named Home 1, Home 2,..... . And they are redirecting to home only . I believe that there is no need of the drop down, so with to remove the dropdown from home button.

### Current Behaviour

Currently home button is having a drop down with several options redirecting to home page only

### Expected Behaviour

Home button will not have any dropdown option

### Reproduction Steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

<img width="481" alt="Screenshot 2023-05-31 at 2 12 25 PM" src="https://github.com/CatsInTech/GitHub-ReadMe/assets/112583158/81815594-2d90-4e8e-8011-858aaacd0860">

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by Khushisharma23** [comment]
Hey @praveenscience I am ready with the solution of this issue can you please assign it to me so that I can go for my PR💥.


![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/98320438/e694ad24-1630-40e0-a965-70f9f951a829)

See now no dropdown menu for home section.

**Comment by praveenscience** [comment]
@singhapeksha As there were no updates from you, I am planning to assign it to @Khushisharma23 right now. Let me know if you have any updates.

@Khushisharma23 Kindly raise the PR if you're ready! 😊
