### ISSUE TITLE
🚀 [New Feature_LP] - Hover effect on social buttons

### ISSUE THREAD

**Issue by sumitkr2000** [CatsInTech/GitHub-ReadMe#58]
### Description of the enhancement. ✍🏻

Hey, @praveenscience I want to add a hover effect on social buttons. On hovering its color changes to the respective official color of social media. Please assign me this issue. Thank you!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add hover effect
2. Step 2
3. Step 3
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by praveenscience** [comment]
Good idea... Show me what you're proposing... 💪🏻

**Comment by praveenscience** [comment]
Nothing is wrong. If you had read the ReadMe, the branch:

* `main` contains the app.
* `website` contains the landing page.

Hope this helps?
