### ISSUE TITLE
Add Sliding tabs while transiting from Latest Tech to Display Store

### ISSUE THREAD

**Issue by dakshsinghrathore** [CatsInTech/GitHub-ReadMe#6]
![Screenshot 2023-05-27 at 10-23-55 GitHub ReadMe Elevating Your Projects   Profile to New Heights!](https://github.com/CatsInTech/GitHub-ReadMe/assets/115932772/f4e6c21a-f90b-4091-97f2-29d9c162b932)

Hey @praveenscience I would like to fix the animation as it does not provide a smooth experience while traversing from Latest Tech to Display Store, kindly assign this issue to me !✌️

**Comment by praveenscience** [comment]
Sure, thanks, make sure you follow the Prettier rules. Looking forward. 💪🏻

Why did you mention GSSoC 23? I specifically asked folks not to mention it right?

**Comment by DSR1729** [comment]
Sorry for the inconvenience @praveenscience , will keep note of it ✅

**Comment by AmanJain18** [comment]
@dakshsinghrathore What's the update ? Final call...
