### ISSUE TITLE
🚀 [New Feature_LP] -SignUP page

### ISSUE THREAD

**Issue by Pragati-3003** [CatsInTech/GitHub-ReadMe#61]
### Description of the enhancement. ✍🏻

I would like to add the signup page for the website .
So , please assign this to me under GSSOC'23.

### Describe briefly how you would implement this enhancement.

```bash
...
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by AmanJain18** [comment]
Is this custom comment is proper ?

**Comment by praveenscience** [comment]
What custom comment @AmanJain18?

**Comment by AmanJain18** [comment]
> ~What custom comment @AmanJain18?~
> Oh yea, looks good, thinking of what to include... 😊 

Sure, Let me know, what more we can add to that. ✌🏻☺️

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?
