### ISSUE TITLE
🚀 [New Feature_LP] - Hover effect on navbar

### ISSUE THREAD

**Issue by mukul314** [CatsInTech/GitHub-ReadMe#68]
### Description of the enhancement. ✍🏻

Currently, when we hover over the navbar only the opacity of the links changes, this is not that attractive. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Instead, we can add hover and transition effects on the links to make them more attractive
```

### Screenshots Example (if applicable)

Look at the below videos for more context :

Before :

https://github.com/CatsInTech/GitHub-ReadMe/assets/76463001/b9f805fe-ddb7-4c7b-b47e-708e4bd28010

After :

https://github.com/CatsInTech/GitHub-ReadMe/assets/76463001/e3c5368a-fb20-4b4b-8c9d-8c572d8f4fba

### Additional information

@praveenscience , I'd like to work on this issue.

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by kaleemullah786** [comment]
hey, i can do this

**Comment by Aditya-Lawate-codez** [comment]
I can do this under SSOC 2.0

**Comment by praveenscience** [comment]
@mukul314 Started this one, let's see if you can do a PR before a day, else it can go to @kaleemullah786 or @Aditya-Lawate-codez, is that alright?

**Comment by mukul314** [comment]
@praveenscience , I have made a PR for the above issue. The PR is #89 .

**Comment by praveenscience** [comment]
@mukul314 Use the right PR template and fill it properly, thanks.
