### ISSUE TITLE
🚀 [New Feature_LP] - Transform scale effect on social buttons

### ISSUE THREAD

**Issue by kar1053** [CatsInTech/GitHub-ReadMe#75]
### Description of the enhancement. ✍🏻

Hey, @ I want to add a hover effect on social buttons using transform property. On hovering its defines a transformation that resizes social buttons on the 2D plane. Please assign me this issue. Thank you!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add Transform scale effect
2. Step 2
3. Step 3
```

### Screenshots Example (if applicable)

Before:

https://github.com/CatsInTech/GitHub-ReadMe/assets/124481653/5a4e3378-ee0d-469a-b3cd-9a309daa287a

After:

https://github.com/CatsInTech/GitHub-ReadMe/assets/124481653/4615607d-7305-427f-a162-3e19356b263f

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by praveenscience** [comment]
@kar1053 Why was this closed? 🤔

**Comment by kar1053** [comment]
@praveenscience I am sorry for this inconvenience. I was create duplicate issue accidentally, can u help me to delete this?

**Comment by praveenscience** [comment]
@kar1053 Issues can unfortunately be not deleted, GitHub's crazy design. It's alright.

**Comment by praveenscience** [comment]
I see only these options man.

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/1830380/5dfa76c1-e81d-4a35-97ee-07cb1bc0756d)

**Comment by kar1053** [comment]
okkk
