### ISSUE TITLE
The scrollbar is not very attractive

### ISSUE THREAD

**Issue by Shreyans2004** [CatsInTech/GitHub-ReadMe#82]
### Description of the enhancement. ✍🏻

The website is beautiful but the scrollbar is very simple.
I can add styling to the scrollbar so that it looks more attractive and the website also looks better.
I can change the styling of scrollbar .Can you assign this issue to me?

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1-I will change the color of scrollbar 
2. Step 2-Adjust its width
3. Step 3-Change its color on hovering
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by praveenscience** [comment]
Okay nice one. Go for it.

**Comment by AmanJain18** [comment]
@Shreyans2004 Use proper template.

**Comment by praveenscience** [comment]
Stale issue, closing.
