### ISSUE TITLE
Missing Code of conduct.md file

### ISSUE THREAD

**Issue by Anshika-Jain02** [CatsInTech/GitHub-ReadMe#91]
Hi there!
I recommend adding a CODE_OF_CONDUCT.md file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under GSSoC'23.

Thank you!

**Comment by praveenscience** [comment]
Sure, which CoC are you planning to use? Also, Why did you mention GSSoC 23? I specifically asked folks not to mention it right?

**Comment by AmanJain18** [comment]
@Anshika-Jain02 This is the duplicate issue

- Check issue #36 

@praveenscience Sir what to do about this. ?

**Comment by praveenscience** [comment]
Yea, #36 was up for grabs, let's close as dupe! 😊
